<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Tenant\Documents\DocumentTemplate;
use Illuminate\Database\Seeder;

/**
 * Seeds system-default document templates (barangay_id = null).
 *
 * These templates are cloned per barangay during onboarding so
 * each barangay starts with a standard set of documents and can
 * then customize them independently.
 *
 * 29 templates across 4 categories:
 * - Resident Certificates (19)
 * - Business/Establishment (3)
 * - Lot/Building (4)
 * - ID Cards (3)
 */
class DefaultDocumentTemplateSeeder extends Seeder
{
    public function run(): void
    {
        $templates = [
            // =====================================================================
            // RESIDENT CERTIFICATES (19)
            // =====================================================================
            [
                'name' => 'Barangay Clearance',
                'category' => 'clearance',
                'constituent_type' => 'resident',
                'title' => 'BARANGAY CLEARANCE',
                'salutation' => 'TO WHOM IT MAY CONCERN:',
                'content' => "This is to certify that {{full_name}}, {{age}} years old, {{sex}}, {{civil_status}}, Filipino Citizen, and a resident of {{address}}, is personally known to be a person of good moral character, trustworthy, diligent and a law-abiding citizen.\n\nRecords in this office show that he/she has no pending case and is not in any way connected with any subversive element or organization.\n\nThis CLEARANCE is being issued upon the request of the above-mentioned name for {{purpose}} purposes.",
                'merge_fields' => ['full_name', 'age', 'sex', 'civil_status', 'address', 'purpose', 'photo_url'],
                'custom_inputs' => [
                    ['name' => 'purpose', 'type' => 'text', 'required' => true, 'label' => 'Purpose'],
                ],
                'approval_config' => [
                    'left' => ['label' => 'Barangay Secretary', 'position' => 'Barangay Secretary'],
                    'right' => ['label' => 'Punong Barangay', 'position' => 'Punong Barangay'],
                ],
                'settings' => [
                    'show_qr' => true,
                    'show_ctc' => true,
                    'show_doc_no' => true,
                    'show_or' => true,
                    'show_expiry' => true,
                    'expiry_months' => 6,
                    'show_photo' => true,
                    'show_thumbmark' => true,
                ],
                'sort_order' => 1,
            ],
            [
                'name' => 'Certificate of Residency',
                'category' => 'residency',
                'constituent_type' => 'resident',
                'title' => 'CERTIFICATE OF RESIDENCY',
                'salutation' => 'TO WHOM IT MAY CONCERN:',
                'content' => "This is to certify that {{full_name}}, {{age}} years old, {{civil_status}}, Filipino, is a bonafide resident of {{address}} for {{years_of_residency}} year(s).\n\nThis certification is being issued upon the request of the above-named person for {{purpose}}.",
                'merge_fields' => ['full_name', 'age', 'civil_status', 'address', 'years_of_residency', 'purpose'],
                'custom_inputs' => [
                    ['name' => 'purpose', 'type' => 'text', 'required' => true, 'label' => 'Purpose'],
                    ['name' => 'years_of_residency', 'type' => 'number', 'required' => true, 'label' => 'Years of Residency'],
                ],
                'approval_config' => [
                    'left' => ['label' => 'Barangay Secretary', 'position' => 'Barangay Secretary'],
                    'right' => ['label' => 'Punong Barangay', 'position' => 'Punong Barangay'],
                ],
                'settings' => [
                    'show_qr' => true,
                    'show_ctc' => true,
                    'show_doc_no' => true,
                    'show_or' => true,
                    'show_expiry' => true,
                    'expiry_months' => 6,
                    'show_photo' => false,
                    'show_thumbmark' => false,
                ],
                'sort_order' => 2,
            ],
            [
                'name' => 'Certificate of Indigency',
                'category' => 'indigency',
                'constituent_type' => 'resident',
                'title' => 'CERTIFICATE OF INDIGENCY',
                'salutation' => 'TO WHOM IT MAY CONCERN:',
                'content' => "This is to certify that {{full_name}}, {{age}} years old, {{civil_status}}, Filipino, and a resident of {{address}}, belongs to the indigent families in this barangay.\n\nThis certification is being issued upon the request of the above-named person for {{purpose}}.",
                'merge_fields' => ['full_name', 'age', 'civil_status', 'address', 'purpose'],
                'custom_inputs' => [
                    ['name' => 'purpose', 'type' => 'text', 'required' => true, 'label' => 'Purpose'],
                ],
                'approval_config' => [
                    'left' => ['label' => 'Barangay Secretary', 'position' => 'Barangay Secretary'],
                    'right' => ['label' => 'Punong Barangay', 'position' => 'Punong Barangay'],
                ],
                'settings' => [
                    'show_qr' => true,
                    'show_ctc' => false,
                    'show_doc_no' => true,
                    'show_or' => false,
                    'show_expiry' => true,
                    'expiry_months' => 3,
                    'show_photo' => false,
                    'show_thumbmark' => false,
                ],
                'sort_order' => 3,
            ],
            [
                'name' => 'Certificate of Indigency (For Relative)',
                'category' => 'indigency_relative',
                'constituent_type' => 'resident',
                'title' => 'CERTIFICATE OF INDIGENCY (FOR RELATIVE)',
                'salutation' => 'TO WHOM IT MAY CONCERN:',
                'content' => "This is to certify that {{full_name}}, {{age}} years old, {{civil_status}}, Filipino, and a resident of {{address}}, is a relative of {{relative_name}} who belongs to the indigent families in this barangay.\n\nThis certification is being issued upon the request of the above-named person on behalf of {{relative_name}} for {{purpose}}.",
                'merge_fields' => ['full_name', 'age', 'civil_status', 'address', 'relative_name', 'purpose'],
                'custom_inputs' => [
                    ['name' => 'relative_name', 'type' => 'text', 'required' => true, 'label' => 'Name of Relative'],
                    ['name' => 'purpose', 'type' => 'text', 'required' => true, 'label' => 'Purpose'],
                ],
                'approval_config' => [
                    'left' => ['label' => 'Barangay Secretary', 'position' => 'Barangay Secretary'],
                    'right' => ['label' => 'Punong Barangay', 'position' => 'Punong Barangay'],
                ],
                'settings' => [
                    'show_qr' => true,
                    'show_ctc' => false,
                    'show_doc_no' => true,
                    'show_or' => false,
                    'show_expiry' => true,
                    'expiry_months' => 3,
                    'show_photo' => false,
                    'show_thumbmark' => false,
                ],
                'sort_order' => 4,
            ],
            [
                'name' => 'Certificate of Good Moral Character',
                'category' => 'good_moral',
                'constituent_type' => 'resident',
                'title' => 'CERTIFICATE OF GOOD MORAL CHARACTER',
                'salutation' => 'TO WHOM IT MAY CONCERN:',
                'content' => "This is to certify that {{full_name}}, {{age}} years old, {{civil_status}}, Filipino, and a resident of {{address}}, is known to be of good moral character and has no pending criminal or administrative case in this barangay.\n\nThis certification is being issued upon the request of the above-named person for {{purpose}}.",
                'merge_fields' => ['full_name', 'age', 'civil_status', 'address', 'purpose'],
                'custom_inputs' => [
                    ['name' => 'purpose', 'type' => 'text', 'required' => true, 'label' => 'Purpose'],
                ],
                'approval_config' => [
                    'left' => ['label' => 'Barangay Secretary', 'position' => 'Barangay Secretary'],
                    'right' => ['label' => 'Punong Barangay', 'position' => 'Punong Barangay'],
                ],
                'settings' => [
                    'show_qr' => true,
                    'show_ctc' => true,
                    'show_doc_no' => true,
                    'show_or' => true,
                    'show_expiry' => true,
                    'expiry_months' => 6,
                    'show_photo' => false,
                    'show_thumbmark' => false,
                ],
                'sort_order' => 5,
            ],
            [
                'name' => 'Community Tax Certificate (Cedula)',
                'category' => 'cedula',
                'constituent_type' => 'resident',
                'title' => 'COMMUNITY TAX CERTIFICATE',
                'salutation' => '',
                'content' => "Issued to {{full_name}}, {{age}} years old, {{civil_status}}, Filipino, resident of {{address}}.\n\nOccupation: {{occupation}}\nGross Annual Income: {{gross_income}}",
                'merge_fields' => ['full_name', 'age', 'civil_status', 'address', 'occupation', 'gross_income'],
                'custom_inputs' => [
                    ['name' => 'occupation', 'type' => 'text', 'required' => false, 'label' => 'Occupation'],
                    ['name' => 'gross_income', 'type' => 'text', 'required' => false, 'label' => 'Gross Annual Income'],
                ],
                'approval_config' => [
                    'right' => ['label' => 'Barangay Treasurer', 'position' => 'Barangay Treasurer'],
                ],
                'settings' => [
                    'show_qr' => false,
                    'show_ctc' => true,
                    'show_doc_no' => true,
                    'show_or' => true,
                    'show_expiry' => true,
                    'expiry_months' => 12,
                    'show_photo' => true,
                    'show_thumbmark' => false,
                ],
                'sort_order' => 6,
            ],
            [
                'name' => 'Certificate of Late Registration',
                'category' => 'late_registration',
                'constituent_type' => 'resident',
                'title' => 'CERTIFICATE OF LATE REGISTRATION',
                'salutation' => 'TO WHOM IT MAY CONCERN:',
                'content' => "This is to certify that {{full_name}}, born on {{birthdate}} at {{birthplace}}, is a resident of {{address}}.\n\nTo the best of our knowledge, the birth/death of the above-named person was not registered in the Local Civil Registry due to {{reason}}.\n\nThis certification is issued for the purpose of securing a late registration at the Local Civil Registrar's Office.",
                'merge_fields' => ['full_name', 'birthdate', 'birthplace', 'address', 'reason'],
                'custom_inputs' => [
                    ['name' => 'birthdate', 'type' => 'date', 'required' => true, 'label' => 'Date of Birth'],
                    ['name' => 'birthplace', 'type' => 'text', 'required' => true, 'label' => 'Place of Birth'],
                    ['name' => 'reason', 'type' => 'text', 'required' => true, 'label' => 'Reason for Late Registration'],
                ],
                'approval_config' => [
                    'left' => ['label' => 'Barangay Secretary', 'position' => 'Barangay Secretary'],
                    'right' => ['label' => 'Punong Barangay', 'position' => 'Punong Barangay'],
                ],
                'settings' => [
                    'show_qr' => true,
                    'show_ctc' => true,
                    'show_doc_no' => true,
                    'show_or' => true,
                    'show_expiry' => false,
                    'show_photo' => false,
                    'show_thumbmark' => false,
                ],
                'sort_order' => 7,
            ],
            [
                'name' => 'Certificate of Live-In / Cohabitation',
                'category' => 'live_in',
                'constituent_type' => 'resident',
                'title' => 'CERTIFICATE OF LIVE-IN / COHABITATION',
                'salutation' => 'TO WHOM IT MAY CONCERN:',
                'content' => "This is to certify that {{full_name}}, {{age}} years old, and {{partner_name}}, {{partner_age}} years old, both residents of {{address}}, have been living together as common-law partners for {{years_together}} year(s).\n\nThis certification is being issued upon the request of the above-named person for {{purpose}}.",
                'merge_fields' => ['full_name', 'age', 'partner_name', 'partner_age', 'address', 'years_together', 'purpose'],
                'custom_inputs' => [
                    ['name' => 'partner_name', 'type' => 'text', 'required' => true, 'label' => "Partner's Full Name"],
                    ['name' => 'partner_age', 'type' => 'number', 'required' => true, 'label' => "Partner's Age"],
                    ['name' => 'years_together', 'type' => 'number', 'required' => true, 'label' => 'Years Living Together'],
                    ['name' => 'purpose', 'type' => 'text', 'required' => true, 'label' => 'Purpose'],
                ],
                'approval_config' => [
                    'left' => ['label' => 'Barangay Secretary', 'position' => 'Barangay Secretary'],
                    'right' => ['label' => 'Punong Barangay', 'position' => 'Punong Barangay'],
                ],
                'settings' => [
                    'show_qr' => true,
                    'show_ctc' => false,
                    'show_doc_no' => true,
                    'show_or' => true,
                    'show_expiry' => true,
                    'expiry_months' => 6,
                    'show_photo' => false,
                    'show_thumbmark' => false,
                ],
                'sort_order' => 8,
            ],
            [
                'name' => 'Certificate of Solo Parent',
                'category' => 'solo_parent',
                'constituent_type' => 'resident',
                'title' => 'CERTIFICATE OF SOLO PARENT',
                'salutation' => 'TO WHOM IT MAY CONCERN:',
                'content' => "This is to certify that {{full_name}}, {{age}} years old, {{civil_status}}, Filipino, and a resident of {{address}}, is a solo parent who solely provides parental care and support to his/her child/children.\n\nThis certification is being issued upon the request of the above-named person for {{purpose}}.",
                'merge_fields' => ['full_name', 'age', 'civil_status', 'address', 'purpose'],
                'custom_inputs' => [
                    ['name' => 'purpose', 'type' => 'text', 'required' => true, 'label' => 'Purpose'],
                ],
                'approval_config' => [
                    'left' => ['label' => 'Barangay Secretary', 'position' => 'Barangay Secretary'],
                    'right' => ['label' => 'Punong Barangay', 'position' => 'Punong Barangay'],
                ],
                'settings' => [
                    'show_qr' => true,
                    'show_ctc' => false,
                    'show_doc_no' => true,
                    'show_or' => false,
                    'show_expiry' => true,
                    'expiry_months' => 6,
                    'show_photo' => false,
                    'show_thumbmark' => false,
                ],
                'sort_order' => 9,
            ],
            [
                'name' => 'Certificate of Low Income',
                'category' => 'low_income',
                'constituent_type' => 'resident',
                'title' => 'CERTIFICATE OF LOW INCOME',
                'salutation' => 'TO WHOM IT MAY CONCERN:',
                'content' => "This is to certify that {{full_name}}, {{age}} years old, {{civil_status}}, Filipino, and a resident of {{address}}, has a monthly income of approximately {{monthly_income}} which is below the poverty threshold.\n\nThis certification is being issued upon the request of the above-named person for {{purpose}}.",
                'merge_fields' => ['full_name', 'age', 'civil_status', 'address', 'monthly_income', 'purpose'],
                'custom_inputs' => [
                    ['name' => 'monthly_income', 'type' => 'text', 'required' => true, 'label' => 'Approximate Monthly Income'],
                    ['name' => 'purpose', 'type' => 'text', 'required' => true, 'label' => 'Purpose'],
                ],
                'approval_config' => [
                    'left' => ['label' => 'Barangay Secretary', 'position' => 'Barangay Secretary'],
                    'right' => ['label' => 'Punong Barangay', 'position' => 'Punong Barangay'],
                ],
                'settings' => [
                    'show_qr' => true,
                    'show_ctc' => false,
                    'show_doc_no' => true,
                    'show_or' => false,
                    'show_expiry' => true,
                    'expiry_months' => 3,
                    'show_photo' => false,
                    'show_thumbmark' => false,
                ],
                'sort_order' => 10,
            ],
            [
                'name' => 'Certificate of No Fixed Income',
                'category' => 'no_fixed_income',
                'constituent_type' => 'resident',
                'title' => 'CERTIFICATE OF NO FIXED INCOME',
                'salutation' => 'TO WHOM IT MAY CONCERN:',
                'content' => "This is to certify that {{full_name}}, {{age}} years old, {{civil_status}}, Filipino, and a resident of {{address}}, has no fixed or regular source of income.\n\nThis certification is being issued upon the request of the above-named person for {{purpose}}.",
                'merge_fields' => ['full_name', 'age', 'civil_status', 'address', 'purpose'],
                'custom_inputs' => [
                    ['name' => 'purpose', 'type' => 'text', 'required' => true, 'label' => 'Purpose'],
                ],
                'approval_config' => [
                    'left' => ['label' => 'Barangay Secretary', 'position' => 'Barangay Secretary'],
                    'right' => ['label' => 'Punong Barangay', 'position' => 'Punong Barangay'],
                ],
                'settings' => [
                    'show_qr' => true,
                    'show_ctc' => false,
                    'show_doc_no' => true,
                    'show_or' => false,
                    'show_expiry' => true,
                    'expiry_months' => 3,
                    'show_photo' => false,
                    'show_thumbmark' => false,
                ],
                'sort_order' => 11,
            ],
            [
                'name' => 'Vehicle Clearance',
                'category' => 'vehicle_clearance',
                'constituent_type' => 'resident',
                'title' => 'VEHICLE CLEARANCE',
                'salutation' => 'TO WHOM IT MAY CONCERN:',
                'content' => "This is to certify that {{full_name}}, {{age}} years old, {{civil_status}}, Filipino, and a resident of {{address}}, is the registered owner/operator of the following vehicle:\n\nType: {{vehicle_type}}\nMake/Brand: {{vehicle_make}}\nPlate Number: {{plate_number}}\nEngine Number: {{engine_number}}\nChassis Number: {{chassis_number}}\n\nThis clearance is being issued for {{purpose}}.",
                'merge_fields' => ['full_name', 'age', 'civil_status', 'address', 'vehicle_type', 'vehicle_make', 'plate_number', 'engine_number', 'chassis_number', 'purpose'],
                'custom_inputs' => [
                    ['name' => 'vehicle_type', 'type' => 'text', 'required' => true, 'label' => 'Vehicle Type'],
                    ['name' => 'vehicle_make', 'type' => 'text', 'required' => true, 'label' => 'Make/Brand'],
                    ['name' => 'plate_number', 'type' => 'text', 'required' => true, 'label' => 'Plate Number'],
                    ['name' => 'engine_number', 'type' => 'text', 'required' => false, 'label' => 'Engine Number'],
                    ['name' => 'chassis_number', 'type' => 'text', 'required' => false, 'label' => 'Chassis Number'],
                    ['name' => 'purpose', 'type' => 'text', 'required' => true, 'label' => 'Purpose'],
                ],
                'approval_config' => [
                    'left' => ['label' => 'Barangay Secretary', 'position' => 'Barangay Secretary'],
                    'right' => ['label' => 'Punong Barangay', 'position' => 'Punong Barangay'],
                ],
                'settings' => [
                    'show_qr' => true,
                    'show_ctc' => false,
                    'show_doc_no' => true,
                    'show_or' => true,
                    'show_expiry' => true,
                    'expiry_months' => 6,
                    'show_photo' => false,
                    'show_thumbmark' => false,
                ],
                'sort_order' => 12,
            ],
            [
                'name' => 'Certificate of No Record',
                'category' => 'no_record',
                'constituent_type' => 'resident',
                'title' => 'CERTIFICATE OF NO RECORD',
                'salutation' => 'TO WHOM IT MAY CONCERN:',
                'content' => "This is to certify that based on available records of this office, {{full_name}}, {{age}} years old, {{civil_status}}, Filipino, and a resident of {{address}}, has NO DEROGATORY RECORD on file in this barangay.\n\nThis certification is being issued upon the request of the above-named person for {{purpose}}.",
                'merge_fields' => ['full_name', 'age', 'civil_status', 'address', 'purpose'],
                'custom_inputs' => [
                    ['name' => 'purpose', 'type' => 'text', 'required' => true, 'label' => 'Purpose'],
                ],
                'approval_config' => [
                    'left' => ['label' => 'Barangay Secretary', 'position' => 'Barangay Secretary'],
                    'right' => ['label' => 'Punong Barangay', 'position' => 'Punong Barangay'],
                ],
                'settings' => [
                    'show_qr' => true,
                    'show_ctc' => true,
                    'show_doc_no' => true,
                    'show_or' => true,
                    'show_expiry' => true,
                    'expiry_months' => 6,
                    'show_photo' => false,
                    'show_thumbmark' => false,
                ],
                'sort_order' => 13,
            ],
            [
                'name' => 'Certificate of Actual Occupancy',
                'category' => 'actual_occupancy',
                'constituent_type' => 'resident',
                'title' => 'CERTIFICATE OF ACTUAL OCCUPANCY',
                'salutation' => 'TO WHOM IT MAY CONCERN:',
                'content' => "This is to certify that {{full_name}}, {{age}} years old, {{civil_status}}, Filipino, is an actual occupant of the property located at {{property_address}} within the jurisdiction of this barangay.\n\nThe above-named person has been occupying the said property for {{years_occupancy}} year(s).\n\nThis certification is being issued upon the request of the above-named person for {{purpose}}.",
                'merge_fields' => ['full_name', 'age', 'civil_status', 'property_address', 'years_occupancy', 'purpose'],
                'custom_inputs' => [
                    ['name' => 'property_address', 'type' => 'text', 'required' => true, 'label' => 'Property Address'],
                    ['name' => 'years_occupancy', 'type' => 'number', 'required' => true, 'label' => 'Years of Occupancy'],
                    ['name' => 'purpose', 'type' => 'text', 'required' => true, 'label' => 'Purpose'],
                ],
                'approval_config' => [
                    'left' => ['label' => 'Barangay Secretary', 'position' => 'Barangay Secretary'],
                    'right' => ['label' => 'Punong Barangay', 'position' => 'Punong Barangay'],
                ],
                'settings' => [
                    'show_qr' => true,
                    'show_ctc' => false,
                    'show_doc_no' => true,
                    'show_or' => true,
                    'show_expiry' => true,
                    'expiry_months' => 6,
                    'show_photo' => false,
                    'show_thumbmark' => false,
                ],
                'sort_order' => 14,
            ],
            [
                'name' => 'Calamity Certificate',
                'category' => 'calamity',
                'constituent_type' => 'resident',
                'title' => 'CALAMITY CERTIFICATE',
                'salutation' => 'TO WHOM IT MAY CONCERN:',
                'content' => "This is to certify that {{full_name}}, {{age}} years old, {{civil_status}}, Filipino, and a resident of {{address}}, is one of the victims/affected residents of {{calamity_name}} that occurred on {{calamity_date}} in this barangay.\n\nThis certification is being issued upon the request of the above-named person for {{purpose}}.",
                'merge_fields' => ['full_name', 'age', 'civil_status', 'address', 'calamity_name', 'calamity_date', 'purpose'],
                'custom_inputs' => [
                    ['name' => 'calamity_name', 'type' => 'text', 'required' => true, 'label' => 'Name of Calamity/Disaster'],
                    ['name' => 'calamity_date', 'type' => 'date', 'required' => true, 'label' => 'Date of Calamity'],
                    ['name' => 'purpose', 'type' => 'text', 'required' => true, 'label' => 'Purpose'],
                ],
                'approval_config' => [
                    'left' => ['label' => 'Barangay Secretary', 'position' => 'Barangay Secretary'],
                    'right' => ['label' => 'Punong Barangay', 'position' => 'Punong Barangay'],
                ],
                'settings' => [
                    'show_qr' => true,
                    'show_ctc' => false,
                    'show_doc_no' => true,
                    'show_or' => false,
                    'show_expiry' => true,
                    'expiry_months' => 3,
                    'show_photo' => false,
                    'show_thumbmark' => false,
                ],
                'sort_order' => 15,
            ],
            [
                'name' => 'First-Time Job Seeker Certificate',
                'category' => 'first_time_job_seeker',
                'constituent_type' => 'resident',
                'title' => 'FIRST-TIME JOB SEEKER CERTIFICATE',
                'salutation' => 'TO WHOM IT MAY CONCERN:',
                'content' => "This is to certify that {{full_name}}, {{age}} years old, {{civil_status}}, Filipino, and a resident of {{address}}, is a first-time job seeker as defined under Republic Act No. 11261 or the First-Time Jobseekers Assistance Act.\n\nThe above-named person has not been previously employed and is availing of the benefits under RA 11261 for the first time.\n\nThis certification is being issued upon the request of the above-named person for employment purposes.",
                'merge_fields' => ['full_name', 'age', 'civil_status', 'address'],
                'custom_inputs' => [],
                'approval_config' => [
                    'left' => ['label' => 'Barangay Secretary', 'position' => 'Barangay Secretary'],
                    'right' => ['label' => 'Punong Barangay', 'position' => 'Punong Barangay'],
                ],
                'settings' => [
                    'show_qr' => true,
                    'show_ctc' => false,
                    'show_doc_no' => true,
                    'show_or' => false,
                    'show_expiry' => true,
                    'expiry_months' => 12,
                    'show_photo' => false,
                    'show_thumbmark' => false,
                ],
                'sort_order' => 16,
            ],
            [
                'name' => 'Senior Citizen Certificate',
                'category' => 'senior_citizen',
                'constituent_type' => 'resident',
                'title' => 'SENIOR CITIZEN CERTIFICATE',
                'salutation' => 'TO WHOM IT MAY CONCERN:',
                'content' => "This is to certify that {{full_name}}, {{age}} years old, {{civil_status}}, Filipino, and a resident of {{address}}, is a bonafide Senior Citizen of this barangay.\n\nSenior Citizen ID No.: {{senior_id_no}}\n\nThis certification is being issued upon the request of the above-named person for {{purpose}}.",
                'merge_fields' => ['full_name', 'age', 'civil_status', 'address', 'senior_id_no', 'purpose'],
                'custom_inputs' => [
                    ['name' => 'senior_id_no', 'type' => 'text', 'required' => false, 'label' => 'Senior Citizen ID No.'],
                    ['name' => 'purpose', 'type' => 'text', 'required' => true, 'label' => 'Purpose'],
                ],
                'approval_config' => [
                    'left' => ['label' => 'Barangay Secretary', 'position' => 'Barangay Secretary'],
                    'right' => ['label' => 'Punong Barangay', 'position' => 'Punong Barangay'],
                ],
                'settings' => [
                    'show_qr' => true,
                    'show_ctc' => false,
                    'show_doc_no' => true,
                    'show_or' => false,
                    'show_expiry' => true,
                    'expiry_months' => 12,
                    'show_photo' => true,
                    'show_thumbmark' => false,
                ],
                'sort_order' => 17,
            ],
            [
                'name' => 'PWD Certificate',
                'category' => 'pwd',
                'constituent_type' => 'resident',
                'title' => 'PWD CERTIFICATE',
                'salutation' => 'TO WHOM IT MAY CONCERN:',
                'content' => "This is to certify that {{full_name}}, {{age}} years old, {{civil_status}}, Filipino, and a resident of {{address}}, is a Person with Disability (PWD) of this barangay.\n\nType of Disability: {{disability_type}}\nPWD ID No.: {{pwd_id_no}}\n\nThis certification is being issued upon the request of the above-named person for {{purpose}}.",
                'merge_fields' => ['full_name', 'age', 'civil_status', 'address', 'disability_type', 'pwd_id_no', 'purpose'],
                'custom_inputs' => [
                    ['name' => 'disability_type', 'type' => 'text', 'required' => true, 'label' => 'Type of Disability'],
                    ['name' => 'pwd_id_no', 'type' => 'text', 'required' => false, 'label' => 'PWD ID No.'],
                    ['name' => 'purpose', 'type' => 'text', 'required' => true, 'label' => 'Purpose'],
                ],
                'approval_config' => [
                    'left' => ['label' => 'Barangay Secretary', 'position' => 'Barangay Secretary'],
                    'right' => ['label' => 'Punong Barangay', 'position' => 'Punong Barangay'],
                ],
                'settings' => [
                    'show_qr' => true,
                    'show_ctc' => false,
                    'show_doc_no' => true,
                    'show_or' => false,
                    'show_expiry' => true,
                    'expiry_months' => 12,
                    'show_photo' => true,
                    'show_thumbmark' => false,
                ],
                'sort_order' => 18,
            ],
            [
                'name' => 'Certificate of Informal Employment',
                'category' => 'informal_employment',
                'constituent_type' => 'resident',
                'title' => 'CERTIFICATE OF INFORMAL EMPLOYMENT',
                'salutation' => 'TO WHOM IT MAY CONCERN:',
                'content' => "This is to certify that {{full_name}}, {{age}} years old, {{civil_status}}, Filipino, and a resident of {{address}}, is informally employed as {{job_description}} in this barangay.\n\nThe above-named person earns an estimated monthly income of {{estimated_income}}.\n\nThis certification is being issued upon the request of the above-named person for {{purpose}}.",
                'merge_fields' => ['full_name', 'age', 'civil_status', 'address', 'job_description', 'estimated_income', 'purpose'],
                'custom_inputs' => [
                    ['name' => 'job_description', 'type' => 'text', 'required' => true, 'label' => 'Job/Work Description'],
                    ['name' => 'estimated_income', 'type' => 'text', 'required' => true, 'label' => 'Estimated Monthly Income'],
                    ['name' => 'purpose', 'type' => 'text', 'required' => true, 'label' => 'Purpose'],
                ],
                'approval_config' => [
                    'left' => ['label' => 'Barangay Secretary', 'position' => 'Barangay Secretary'],
                    'right' => ['label' => 'Punong Barangay', 'position' => 'Punong Barangay'],
                ],
                'settings' => [
                    'show_qr' => true,
                    'show_ctc' => false,
                    'show_doc_no' => true,
                    'show_or' => true,
                    'show_expiry' => true,
                    'expiry_months' => 6,
                    'show_photo' => false,
                    'show_thumbmark' => false,
                ],
                'sort_order' => 19,
            ],

            // =====================================================================
            // BUSINESS / ESTABLISHMENT (3)
            // =====================================================================
            [
                'name' => 'Business Clearance (New)',
                'category' => 'business_clearance_new',
                'constituent_type' => 'establishment',
                'title' => 'BARANGAY BUSINESS CLEARANCE',
                'salutation' => 'TO WHOM IT MAY CONCERN:',
                'content' => "This is to certify that {{business_name}}, owned and operated by {{owner_name}}, located at {{business_address}}, has been granted clearance to operate within the jurisdiction of this barangay.\n\nNature of Business: {{nature_of_business}}\n\nThis clearance is being issued for NEW BUSINESS REGISTRATION purposes.",
                'merge_fields' => ['business_name', 'owner_name', 'business_address', 'nature_of_business'],
                'custom_inputs' => [
                    ['name' => 'business_name', 'type' => 'text', 'required' => true, 'label' => 'Business Name'],
                    ['name' => 'owner_name', 'type' => 'text', 'required' => true, 'label' => 'Owner Name'],
                    ['name' => 'business_address', 'type' => 'text', 'required' => true, 'label' => 'Business Address'],
                    ['name' => 'nature_of_business', 'type' => 'text', 'required' => true, 'label' => 'Nature of Business'],
                ],
                'approval_config' => [
                    'left' => ['label' => 'Barangay Secretary', 'position' => 'Barangay Secretary'],
                    'right' => ['label' => 'Punong Barangay', 'position' => 'Punong Barangay'],
                ],
                'settings' => [
                    'show_qr' => true,
                    'show_ctc' => false,
                    'show_doc_no' => true,
                    'show_or' => true,
                    'show_expiry' => true,
                    'expiry_months' => 12,
                    'show_photo' => false,
                    'show_thumbmark' => false,
                ],
                'sort_order' => 20,
            ],
            [
                'name' => 'Business Clearance (Renewal)',
                'category' => 'business_clearance_renewal',
                'constituent_type' => 'establishment',
                'title' => 'BARANGAY BUSINESS CLEARANCE (RENEWAL)',
                'salutation' => 'TO WHOM IT MAY CONCERN:',
                'content' => "This is to certify that {{business_name}}, owned and operated by {{owner_name}}, located at {{business_address}}, has been granted clearance to continue its operations within the jurisdiction of this barangay.\n\nNature of Business: {{nature_of_business}}\nPrevious Permit No.: {{prev_permit_no}}\n\nThis clearance is being issued for BUSINESS RENEWAL purposes.",
                'merge_fields' => ['business_name', 'owner_name', 'business_address', 'nature_of_business', 'prev_permit_no'],
                'custom_inputs' => [
                    ['name' => 'business_name', 'type' => 'text', 'required' => true, 'label' => 'Business Name'],
                    ['name' => 'owner_name', 'type' => 'text', 'required' => true, 'label' => 'Owner Name'],
                    ['name' => 'business_address', 'type' => 'text', 'required' => true, 'label' => 'Business Address'],
                    ['name' => 'nature_of_business', 'type' => 'text', 'required' => true, 'label' => 'Nature of Business'],
                    ['name' => 'prev_permit_no', 'type' => 'text', 'required' => false, 'label' => 'Previous Permit Number'],
                ],
                'approval_config' => [
                    'left' => ['label' => 'Barangay Secretary', 'position' => 'Barangay Secretary'],
                    'right' => ['label' => 'Punong Barangay', 'position' => 'Punong Barangay'],
                ],
                'settings' => [
                    'show_qr' => true,
                    'show_ctc' => false,
                    'show_doc_no' => true,
                    'show_or' => true,
                    'show_expiry' => true,
                    'expiry_months' => 12,
                    'show_photo' => false,
                    'show_thumbmark' => false,
                ],
                'sort_order' => 21,
            ],
            [
                'name' => 'Business Closure Clearance',
                'category' => 'business_closure',
                'constituent_type' => 'establishment',
                'title' => 'BARANGAY BUSINESS CLOSURE CLEARANCE',
                'salutation' => 'TO WHOM IT MAY CONCERN:',
                'content' => "This is to certify that {{business_name}}, owned and operated by {{owner_name}}, located at {{business_address}}, has ceased its business operations effective {{closure_date}}.\n\nNature of Business: {{nature_of_business}}\nReason for Closure: {{closure_reason}}\n\nThis clearance is being issued to confirm the closure of the above-mentioned business establishment.",
                'merge_fields' => ['business_name', 'owner_name', 'business_address', 'nature_of_business', 'closure_date', 'closure_reason'],
                'custom_inputs' => [
                    ['name' => 'business_name', 'type' => 'text', 'required' => true, 'label' => 'Business Name'],
                    ['name' => 'owner_name', 'type' => 'text', 'required' => true, 'label' => 'Owner Name'],
                    ['name' => 'business_address', 'type' => 'text', 'required' => true, 'label' => 'Business Address'],
                    ['name' => 'nature_of_business', 'type' => 'text', 'required' => true, 'label' => 'Nature of Business'],
                    ['name' => 'closure_date', 'type' => 'date', 'required' => true, 'label' => 'Date of Closure'],
                    ['name' => 'closure_reason', 'type' => 'text', 'required' => true, 'label' => 'Reason for Closure'],
                ],
                'approval_config' => [
                    'left' => ['label' => 'Barangay Secretary', 'position' => 'Barangay Secretary'],
                    'right' => ['label' => 'Punong Barangay', 'position' => 'Punong Barangay'],
                ],
                'settings' => [
                    'show_qr' => true,
                    'show_ctc' => false,
                    'show_doc_no' => true,
                    'show_or' => true,
                    'show_expiry' => false,
                    'show_photo' => false,
                    'show_thumbmark' => false,
                ],
                'sort_order' => 22,
            ],

            // =====================================================================
            // LOT / BUILDING (4)
            // =====================================================================
            [
                'name' => 'Lot Clearance',
                'category' => 'lot_clearance',
                'constituent_type' => 'lot_building',
                'title' => 'BARANGAY LOT CLEARANCE',
                'salutation' => 'TO WHOM IT MAY CONCERN:',
                'content' => "This is to certify that {{owner_name}}, the owner of the lot/property located at {{lot_address}}, has been granted clearance by this Barangay for {{purpose}}.\n\nLot Area: {{lot_area}} sq.m.\nTCT/Tax Declaration No.: {{tax_dec_no}}",
                'merge_fields' => ['owner_name', 'lot_address', 'purpose', 'lot_area', 'tax_dec_no'],
                'custom_inputs' => [
                    ['name' => 'owner_name', 'type' => 'text', 'required' => true, 'label' => 'Lot Owner Name'],
                    ['name' => 'lot_address', 'type' => 'text', 'required' => true, 'label' => 'Lot Address'],
                    ['name' => 'purpose', 'type' => 'text', 'required' => true, 'label' => 'Purpose'],
                    ['name' => 'lot_area', 'type' => 'text', 'required' => false, 'label' => 'Lot Area (sq.m.)'],
                    ['name' => 'tax_dec_no', 'type' => 'text', 'required' => false, 'label' => 'TCT/Tax Dec No.'],
                ],
                'approval_config' => [
                    'left' => ['label' => 'Barangay Secretary', 'position' => 'Barangay Secretary'],
                    'right' => ['label' => 'Punong Barangay', 'position' => 'Punong Barangay'],
                ],
                'settings' => [
                    'show_qr' => true,
                    'show_ctc' => false,
                    'show_doc_no' => true,
                    'show_or' => true,
                    'show_expiry' => true,
                    'expiry_months' => 12,
                    'show_photo' => false,
                    'show_thumbmark' => false,
                ],
                'sort_order' => 23,
            ],
            [
                'name' => 'Building / Construction Clearance',
                'category' => 'building_clearance',
                'constituent_type' => 'lot_building',
                'title' => 'BARANGAY BUILDING / CONSTRUCTION CLEARANCE',
                'salutation' => 'TO WHOM IT MAY CONCERN:',
                'content' => "This is to certify that {{owner_name}}, a resident of {{owner_address}}, has been granted clearance to construct/renovate a {{structure_type}} at {{construction_address}} within the jurisdiction of this barangay.\n\nProject Description: {{project_description}}\nEstimated Floor Area: {{floor_area}} sq.m.",
                'merge_fields' => ['owner_name', 'owner_address', 'structure_type', 'construction_address', 'project_description', 'floor_area'],
                'custom_inputs' => [
                    ['name' => 'owner_name', 'type' => 'text', 'required' => true, 'label' => 'Owner Name'],
                    ['name' => 'owner_address', 'type' => 'text', 'required' => true, 'label' => "Owner's Address"],
                    ['name' => 'structure_type', 'type' => 'text', 'required' => true, 'label' => 'Type of Structure'],
                    ['name' => 'construction_address', 'type' => 'text', 'required' => true, 'label' => 'Construction Site Address'],
                    ['name' => 'project_description', 'type' => 'text', 'required' => false, 'label' => 'Project Description'],
                    ['name' => 'floor_area', 'type' => 'text', 'required' => false, 'label' => 'Estimated Floor Area (sq.m.)'],
                ],
                'approval_config' => [
                    'left' => ['label' => 'Barangay Secretary', 'position' => 'Barangay Secretary'],
                    'right' => ['label' => 'Punong Barangay', 'position' => 'Punong Barangay'],
                ],
                'settings' => [
                    'show_qr' => true,
                    'show_ctc' => false,
                    'show_doc_no' => true,
                    'show_or' => true,
                    'show_expiry' => true,
                    'expiry_months' => 12,
                    'show_photo' => false,
                    'show_thumbmark' => false,
                ],
                'sort_order' => 24,
            ],
            [
                'name' => 'Fencing Clearance',
                'category' => 'fencing_clearance',
                'constituent_type' => 'lot_building',
                'title' => 'BARANGAY FENCING CLEARANCE',
                'salutation' => 'TO WHOM IT MAY CONCERN:',
                'content' => "This is to certify that {{owner_name}}, the owner of the property located at {{property_address}}, has been granted clearance to construct a fence around the said property.\n\nFence Type: {{fence_type}}\nFence Height: {{fence_height}}\nTotal Length: {{fence_length}}",
                'merge_fields' => ['owner_name', 'property_address', 'fence_type', 'fence_height', 'fence_length'],
                'custom_inputs' => [
                    ['name' => 'owner_name', 'type' => 'text', 'required' => true, 'label' => 'Owner Name'],
                    ['name' => 'property_address', 'type' => 'text', 'required' => true, 'label' => 'Property Address'],
                    ['name' => 'fence_type', 'type' => 'text', 'required' => true, 'label' => 'Type of Fence'],
                    ['name' => 'fence_height', 'type' => 'text', 'required' => false, 'label' => 'Fence Height'],
                    ['name' => 'fence_length', 'type' => 'text', 'required' => false, 'label' => 'Total Fence Length'],
                ],
                'approval_config' => [
                    'left' => ['label' => 'Barangay Secretary', 'position' => 'Barangay Secretary'],
                    'right' => ['label' => 'Punong Barangay', 'position' => 'Punong Barangay'],
                ],
                'settings' => [
                    'show_qr' => true,
                    'show_ctc' => false,
                    'show_doc_no' => true,
                    'show_or' => true,
                    'show_expiry' => true,
                    'expiry_months' => 12,
                    'show_photo' => false,
                    'show_thumbmark' => false,
                ],
                'sort_order' => 25,
            ],
            [
                'name' => 'Excavation / Digging Clearance',
                'category' => 'excavation_clearance',
                'constituent_type' => 'lot_building',
                'title' => 'BARANGAY EXCAVATION / DIGGING CLEARANCE',
                'salutation' => 'TO WHOM IT MAY CONCERN:',
                'content' => "This is to certify that {{applicant_name}} has been granted clearance to conduct excavation/digging activities at {{site_address}} within the jurisdiction of this barangay.\n\nPurpose of Excavation: {{excavation_purpose}}\nEstimated Duration: {{duration}}\nArea Affected: {{affected_area}}",
                'merge_fields' => ['applicant_name', 'site_address', 'excavation_purpose', 'duration', 'affected_area'],
                'custom_inputs' => [
                    ['name' => 'applicant_name', 'type' => 'text', 'required' => true, 'label' => 'Applicant Name'],
                    ['name' => 'site_address', 'type' => 'text', 'required' => true, 'label' => 'Site Address'],
                    ['name' => 'excavation_purpose', 'type' => 'text', 'required' => true, 'label' => 'Purpose of Excavation'],
                    ['name' => 'duration', 'type' => 'text', 'required' => false, 'label' => 'Estimated Duration'],
                    ['name' => 'affected_area', 'type' => 'text', 'required' => false, 'label' => 'Area Affected'],
                ],
                'approval_config' => [
                    'left' => ['label' => 'Barangay Secretary', 'position' => 'Barangay Secretary'],
                    'right' => ['label' => 'Punong Barangay', 'position' => 'Punong Barangay'],
                ],
                'settings' => [
                    'show_qr' => true,
                    'show_ctc' => false,
                    'show_doc_no' => true,
                    'show_or' => true,
                    'show_expiry' => true,
                    'expiry_months' => 6,
                    'show_photo' => false,
                    'show_thumbmark' => false,
                ],
                'sort_order' => 26,
            ],

            // =====================================================================
            // ID CARDS (3)
            // =====================================================================
            [
                'name' => 'Barangay ID',
                'category' => 'barangay_id',
                'constituent_type' => 'resident',
                'title' => 'BARANGAY IDENTIFICATION CARD',
                'salutation' => '',
                'content' => "{{full_name}}\n{{address}}\nDate of Birth: {{birthdate}}\nSex: {{sex}}\nCivil Status: {{civil_status}}\nBlood Type: {{blood_type}}\nContact No.: {{contact_number}}\nEmergency Contact: {{emergency_contact}}\nEmergency Contact No.: {{emergency_number}}",
                'merge_fields' => ['full_name', 'address', 'birthdate', 'sex', 'civil_status', 'blood_type', 'contact_number', 'emergency_contact', 'emergency_number', 'photo_url'],
                'custom_inputs' => [
                    ['name' => 'blood_type', 'type' => 'text', 'required' => false, 'label' => 'Blood Type'],
                    ['name' => 'emergency_contact', 'type' => 'text', 'required' => true, 'label' => 'Emergency Contact Person'],
                    ['name' => 'emergency_number', 'type' => 'text', 'required' => true, 'label' => 'Emergency Contact Number'],
                ],
                'approval_config' => [
                    'right' => ['label' => 'Punong Barangay', 'position' => 'Punong Barangay'],
                ],
                'settings' => [
                    'show_qr' => true,
                    'show_ctc' => false,
                    'show_doc_no' => true,
                    'show_or' => false,
                    'show_expiry' => true,
                    'expiry_months' => 36,
                    'show_photo' => true,
                    'show_thumbmark' => true,
                ],
                'sort_order' => 27,
            ],
            [
                'name' => 'Family ID',
                'category' => 'family_id',
                'constituent_type' => 'resident',
                'title' => 'BARANGAY FAMILY IDENTIFICATION CARD',
                'salutation' => '',
                'content' => "{{full_name}} (Head of Family)\n{{address}}\nContact No.: {{contact_number}}\n\nFamily Members:\n{{family_members}}",
                'merge_fields' => ['full_name', 'address', 'contact_number', 'family_members', 'photo_url'],
                'custom_inputs' => [],
                'approval_config' => [
                    'right' => ['label' => 'Punong Barangay', 'position' => 'Punong Barangay'],
                ],
                'settings' => [
                    'show_qr' => true,
                    'show_ctc' => false,
                    'show_doc_no' => true,
                    'show_or' => false,
                    'show_expiry' => true,
                    'expiry_months' => 36,
                    'show_photo' => true,
                    'show_thumbmark' => false,
                ],
                'sort_order' => 28,
            ],
            [
                'name' => 'Barangay Staff ID',
                'category' => 'staff_id',
                'constituent_type' => 'resident',
                'title' => 'BARANGAY STAFF IDENTIFICATION CARD',
                'salutation' => '',
                'content' => "{{full_name}}\n{{position}}\n{{address}}\nDate of Birth: {{birthdate}}\nSex: {{sex}}\nContact No.: {{contact_number}}\nEmergency Contact: {{emergency_contact}}\nEmergency Contact No.: {{emergency_number}}",
                'merge_fields' => ['full_name', 'position', 'address', 'birthdate', 'sex', 'contact_number', 'emergency_contact', 'emergency_number', 'photo_url'],
                'custom_inputs' => [
                    ['name' => 'position', 'type' => 'text', 'required' => true, 'label' => 'Position/Designation'],
                    ['name' => 'emergency_contact', 'type' => 'text', 'required' => true, 'label' => 'Emergency Contact Person'],
                    ['name' => 'emergency_number', 'type' => 'text', 'required' => true, 'label' => 'Emergency Contact Number'],
                ],
                'approval_config' => [
                    'right' => ['label' => 'Punong Barangay', 'position' => 'Punong Barangay'],
                ],
                'settings' => [
                    'show_qr' => true,
                    'show_ctc' => false,
                    'show_doc_no' => true,
                    'show_or' => false,
                    'show_expiry' => true,
                    'expiry_months' => 36,
                    'show_photo' => true,
                    'show_thumbmark' => true,
                ],
                'sort_order' => 29,
            ],
        ];

        foreach ($templates as $template) {
            DocumentTemplate::firstOrCreate(
                [
                    'barangay_id' => null,
                    'category' => $template['category'],
                ],
                array_merge($template, [
                    'barangay_id' => null,
                    'status' => 'active',
                ]),
            );
        }
    }
}
