import type {
  Alert,
  MabiniInsight,
  DropletMetrics,
  DatabaseStatus,
  ProductHealth,
  RevenueData,
  DomainStatus,
  Deployment,
  SecurityFeed,
  ActivityEvent,
} from "./types";

export const mockAlerts: Alert[] = [
  {
    id: "alert-1",
    severity: "warning",
    title: "PrimeXV4 RAM Usage High",
    description:
      "RAM usage on PrimeXV4 (128.199.172.45) has been above 85% for the last 2 hours. Consider investigating memory-heavy processes.",
    source: "infrastructure-monitor",
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    acknowledged: false,
  },
];

export const mockInsight: MabiniInsight = {
  summary:
    "All systems are operational. BCMP staging is healthy with 76 tests passing. PrimeXV4 RAM usage is elevated at 85% average -- this is expected with 50+ active barangays. Revenue is stable at ~83K MRR. No critical security incidents in the last 24 hours. The V5 migration from V4 is on track.",
  analyzed_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  highlights: [
    "BCMP V5 staging API: 200+ routes, all tests passing",
    "PrimeXV4 cannot be downsized due to RAM constraints",
    "DO monthly spend: ~255 PHP/month (optimized)",
    "Next priority: wire New Resident form to bcmp-api",
  ],
};

export const mockDroplets: DropletMetrics[] = [
  {
    id: "primexv4",
    name: "PrimeXV4",
    ip: "128.199.172.45",
    status: "active",
    region: "SGP1",
    spec: "2vCPU / 8GB",
    cpu_percent: 13,
    ram_percent: 85,
    disk_percent: 42,
    uptime_seconds: 2592000,
  },
  {
    id: "pulitika-staging",
    name: "pulitika-staging",
    ip: "159.89.207.105",
    status: "active",
    region: "SGP1",
    spec: "1vCPU / 2GB",
    cpu_percent: 8,
    ram_percent: 28,
    disk_percent: 15,
    uptime_seconds: 604800,
  },
  {
    id: "staging-server",
    name: "Staging-Server",
    ip: "152.42.252.6",
    status: "active",
    region: "SGP1",
    spec: "2vCPU / 4GB",
    cpu_percent: 5,
    ram_percent: 35,
    disk_percent: 30,
    uptime_seconds: 1209600,
  },
  {
    id: "spa-call",
    name: "spa-call",
    ip: "152.42.238.242",
    status: "active",
    region: "SGP1",
    spec: "1vCPU / 1GB",
    cpu_percent: 3,
    ram_percent: 52,
    disk_percent: 25,
    uptime_seconds: 1728000,
  },
  {
    id: "tarlac-assets",
    name: "tarlac-assets",
    ip: "137.184.249.255",
    status: "active",
    region: "SGP1",
    spec: "1vCPU / 1GB",
    cpu_percent: 4,
    ram_percent: 48,
    disk_percent: 18,
    uptime_seconds: 1728000,
  },
  {
    id: "barangaymo",
    name: "BarangayMo",
    ip: "174.138.21.22",
    status: "active",
    region: "SGP1",
    spec: "1vCPU / 1GB",
    cpu_percent: 2,
    ram_percent: 45,
    disk_percent: 20,
    uptime_seconds: 2160000,
  },
];

export const mockDatabases: DatabaseStatus[] = [
  {
    id: "db-mysql-v4",
    name: "db-mysql-v4",
    engine: "MySQL",
    version: "8.0",
    status: "online",
    connection_count: 24,
    size_bytes: 2147483648,
    host: "private",
  },
  {
    id: "pulitika-staging-db",
    name: "pulitika-staging-db",
    engine: "PostgreSQL",
    version: "17",
    status: "online",
    connection_count: 8,
    size_bytes: 134217728,
    host: "private",
  },
  {
    id: "primex-staging-db",
    name: "primex-stagin-db",
    engine: "PostgreSQL",
    version: "18",
    status: "online",
    connection_count: 5,
    size_bytes: 268435456,
    host: "private",
  },
  {
    id: "spacall-db",
    name: "spacall-db",
    engine: "PostgreSQL",
    version: "18",
    status: "online",
    connection_count: 3,
    size_bytes: 104857600,
    host: "private",
  },
  {
    id: "tarlac-db",
    name: "tarlac-db",
    engine: "PostgreSQL",
    version: "18",
    status: "online",
    connection_count: 12,
    size_bytes: 536870912,
    host: "private",
  },
];

export const mockProductHealth: ProductHealth[] = [
  {
    product: "Kapitan.ph V5",
    slug: "bcmp",
    api_status: "healthy",
    response_time_ms: 142,
    error_rate: 0.1,
    active_users: 0,
    last_checked_at: new Date().toISOString(),
  },
  {
    product: "Tarlac.ph",
    slug: "lgmp",
    api_status: "healthy",
    response_time_ms: 89,
    error_rate: 0.3,
    active_users: 28,
    last_checked_at: new Date().toISOString(),
  },
  {
    product: "PDMP",
    slug: "pdmp",
    api_status: "unknown",
    response_time_ms: 0,
    error_rate: 0,
    active_users: 0,
    last_checked_at: new Date().toISOString(),
  },
];

export const mockRevenue: RevenueData[] = [
  { month: "Oct 2025", bcmp: 80000, lgmp: 250000, pdmp: 0, total: 330000 },
  { month: "Nov 2025", bcmp: 78000, lgmp: 250000, pdmp: 0, total: 328000 },
  { month: "Dec 2025", bcmp: 82000, lgmp: 250000, pdmp: 0, total: 332000 },
  { month: "Jan 2026", bcmp: 85000, lgmp: 250000, pdmp: 0, total: 335000 },
  { month: "Feb 2026", bcmp: 83000, lgmp: 250000, pdmp: 0, total: 333000 },
  { month: "Mar 2026", bcmp: 83000, lgmp: 250000, pdmp: 0, total: 333000 },
];

export const mockDomains: DomainStatus[] = [
  { domain: "kapitan.ph", ssl_status: "active", proxy_status: "proxied", plan: "Free", product_group: "BCMP" },
  { domain: "kabataan.ph", ssl_status: "active", proxy_status: "proxied", plan: "Free", product_group: "BCMP" },
  { domain: "barangay.org.ph", ssl_status: "active", proxy_status: "proxied", plan: "Free", product_group: "BCMP" },
  { domain: "pulitika.ph", ssl_status: "active", proxy_status: "proxied", plan: "Free", product_group: "Admin" },
  { domain: "primex.ventures", ssl_status: "active", proxy_status: "proxied", plan: "Free", product_group: "Corporate" },
  { domain: "tarlac.ph", ssl_status: "active", proxy_status: "proxied", plan: "Free", product_group: "LGMP" },
  { domain: "spacall.ph", ssl_status: "active", proxy_status: "proxied", plan: "Free", product_group: "SPACALL" },
  { domain: "barangaymo.com", ssl_status: "active", proxy_status: "proxied", plan: "Pro", product_group: "Barangaymo" },
  { domain: "vantagehunt.com", ssl_status: "active", proxy_status: "proxied", plan: "Free", product_group: "VantageHunt" },
  { domain: "robes.ph", ssl_status: "active", proxy_status: "proxied", plan: "Free", product_group: "PDMP" },
  { domain: "sdn.ph", ssl_status: "active", proxy_status: "proxied", plan: "Free", product_group: "Legacy" },
  { domain: "gobernor.ph", ssl_status: "active", proxy_status: "dns_only", plan: "Free", product_group: "Parked" },
  { domain: "kongreso.ph", ssl_status: "active", proxy_status: "proxied", plan: "Free", product_group: "Parked" },
  { domain: "senador.ph", ssl_status: "active", proxy_status: "proxied", plan: "Free", product_group: "Parked" },
  { domain: "gpptradingandservices.com", ssl_status: "active", proxy_status: "proxied", plan: "Free", product_group: "External" },
];

export const mockDeployments: Deployment[] = [
  {
    id: "deploy-1",
    project_name: "bcmp-web",
    branch: "main",
    status: "success",
    commit_message: "Apply 12 Non-Negotiable Principles to all 21 dashboard pages",
    triggered_by: "Claude",
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    duration_seconds: 94,
  },
  {
    id: "deploy-2",
    project_name: "bcmp-api",
    branch: "main",
    status: "success",
    commit_message: "Add Smart Photo System with tanga-proof camera error handling",
    triggered_by: "Claude",
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    duration_seconds: 68,
  },
  {
    id: "deploy-3",
    project_name: "pulitika-web",
    branch: "main",
    status: "success",
    commit_message: "Orange accent color scheme applied, Command Center landing",
    triggered_by: "Claude",
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    duration_seconds: 82,
  },
  {
    id: "deploy-4",
    project_name: "pulitika-api",
    branch: "main",
    status: "success",
    commit_message: "Deploy staging with PHP-FPM + Nginx, 80 Pest tests passing",
    triggered_by: "Claude",
    created_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    duration_seconds: 55,
  },
];

export const mockSecurityFeed: SecurityFeed = {
  failed_logins_24h: 12,
  blocked_requests_24h: 847,
  suspicious_ips: [
    { ip: "185.220.101.34", attempts: 23, last_seen: new Date(Date.now() - 45 * 60 * 1000).toISOString(), country: "RU" },
    { ip: "91.240.118.72", attempts: 15, last_seen: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), country: "CN" },
    { ip: "45.33.32.156", attempts: 8, last_seen: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(), country: "US" },
  ],
  last_updated_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
};

export const mockActivity: ActivityEvent[] = [
  {
    id: "act-1",
    action: "CI/CD Pipeline Passed",
    actor: "Claude",
    product: "bcmp",
    description: "bcmp-web deployed to staging-bcmp.primex.ventures successfully",
    timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: "act-2",
    action: "76 Tests Passed",
    actor: "Claude",
    product: "bcmp",
    description: "All Pest tests green on bcmp-api main branch",
    timestamp: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: "act-3",
    action: "Documentation Updated",
    actor: "Claude",
    product: "pulitika",
    description: "BCMP Master Doc updated with 29 pages across 5 sections",
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "act-4",
    action: "Server Downsized",
    actor: "System",
    product: "system",
    description: "spa-call droplet downsized from s-2vcpu-4gb to s-1vcpu-1gb",
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "act-5",
    action: "Firewall Deleted",
    actor: "Claude",
    product: "system",
    description: "automation-server firewall removed after n8n server deletion",
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "act-6",
    action: "Login Detected",
    actor: "Jeager",
    product: "lgmp",
    description: "Successful login from 210.4.96.245 (PH) on tarlac.ph",
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "act-7",
    action: "Dev Team Pulled",
    actor: "Jeager",
    product: "system",
    description: "All development moved to Claude + Jeager. Dev team on standby.",
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
];
