<?php

declare(strict_types=1);

namespace App\Services;

use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

class TelegramService
{
    private string $botToken;

    private string $chatId;

    private string $baseUrl = 'https://api.telegram.org';

    public function __construct()
    {
        $this->botToken = (string) config('services.telegram.bot_token');
        $this->chatId = (string) config('services.telegram.chat_id');
    }

    /**
     * Send a plain text message to the configured Telegram chat.
     */
    public function sendMessage(string $text, ?string $parseMode = 'HTML'): bool
    {
        if ($this->botToken === '' || $this->chatId === '') {
            Log::warning('Telegram: bot_token or chat_id not configured, skipping message');

            return false;
        }

        try {
            $response = Http::timeout(5)
                ->post("{$this->baseUrl}/bot{$this->botToken}/sendMessage", [
                    'chat_id' => $this->chatId,
                    'text' => $text,
                    'parse_mode' => $parseMode,
                    'disable_web_page_preview' => true,
                ]);

            if ($response->failed()) {
                Log::error('Telegram: failed to send message', [
                    'status' => $response->status(),
                    'body' => $response->body(),
                ]);

                return false;
            }

            return true;
        } catch (\Exception $e) {
            Log::error('Telegram: send message exception', [
                'error' => $e->getMessage(),
            ]);

            return false;
        }
    }

    /**
     * Send a formatted alert message with severity badge.
     */
    public function sendAlert(string $severity, string $title, string $message): bool
    {
        $severityEmoji = match ($severity) {
            'critical' => 'CRITICAL',
            'warning' => 'WARNING',
            'info' => 'INFO',
            default => strtoupper($severity),
        };

        $text = "<b>[{$severityEmoji}] {$title}</b>\n\n{$message}\n\n<i>PrimeX Command Center</i>";

        return $this->sendMessage($text);
    }

    /**
     * Send a daily briefing summary.
     */
    public function sendBriefing(string $summary): bool
    {
        $text = "<b>PrimeX Daily Briefing</b>\n"
            .str_repeat('-', 30)."\n\n"
            .$summary."\n\n"
            .'<i>Generated by Mabini AI</i>';

        return $this->sendMessage($text);
    }
}
